# Generated by Django 2.0.4 on 2018-05-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=20, null=True, unique=True)),
                ('project', models.CharField(blank=True, db_column='PROJECT', max_length=200, null=True)),
                ('position', models.CharField(blank=True, db_column='POSITION', max_length=100, null=True)),
                ('contract_place', models.CharField(blank=True, db_column='CONTRACT_PLACE', max_length=20, null=True)),
                ('hire_date', models.DateField(blank=True, db_column='HIRE_DATE', null=True)),
                ('st_work_date', models.DateField(blank=True, db_column='ST_WORK_DATE', null=True)),
            ],
            options={
                'db_table': 'PERSON_INFO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('projectName', models.CharField(max_length=200)),
            ],
        ),
    ]
