# Generated by Django 2.0.4 on 2018-06-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipm', '0002_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentText', models.CharField(max_length=200)),
                ('estAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estPayDate', models.DateField()),
                ('actPayDate', models.DateField()),
                ('invoicePercent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('invoiceStatus', models.BooleanField()),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipm.ProjectInfo')),
            ],
        ),
    ]
