# Generated by Django 2.0.4 on 2018-07-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipm', '0003_invoicetracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('finish', models.BooleanField()),
                ('remark', models.TextField()),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipm.ProjectInfo')),
            ],
        ),
    ]
