# Generated by Django 2.0.4 on 2018-07-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipm', '0004_workdaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicDetailName', models.CharField(max_length=300)),
                ('dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipm.Dict')),
            ],
        ),
    ]
