# Generated by Django 2.0.4 on 2018-07-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipm', '0005_dicdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('workloadTarget', models.DecimalField(decimal_places=4, max_digits=10)),
                ('incomeTarget', models.DecimalField(decimal_places=4, max_digits=10)),
                ('costTarget', models.DecimalField(decimal_places=4, max_digits=10)),
                ('incomePerPerson', models.DecimalField(decimal_places=4, max_digits=10)),
                ('marginTarget', models.DecimalField(decimal_places=4, max_digits=10)),
                ('projectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipm.ProjectInfo')),
            ],
        ),
    ]
