# Generated by Django 2.0.4 on 2018-07-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipm', '0006_projecttarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttarget',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projecttarget',
            name='versionNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projecttarget',
            name='costTarget',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projecttarget',
            name='incomePerPerson',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projecttarget',
            name='incomeTarget',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projecttarget',
            name='marginTarget',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projecttarget',
            name='workloadTarget',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workdaily',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workdaily',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='workdaily',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
